application: cardmemoriae
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(png|svg|css|js|html|json))
  static_files: static/\1
  upload: static/(.*\.(png|svg|css|js|html|json))
  
- url: /.*
  script: main.py